-- 1. notes 테이블 생성 (owner_id 컬럼을 미리 두되, auth.users 외래키는 연결하지 않음)
CREATE TABLE IF NOT EXISTS notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  owner_id uuid,
  created_at timestamptz DEFAULT now()
);

-- 2. Row Level Security(RLS) 활성화
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- 3. anon 및 authenticated 역할에 테이블 읽기(SELECT)를 포함한 권한 부여 방지 (RLS 기본 차단 유지 및 권한 회수)
REVOKE ALL ON TABLE notes FROM anon, authenticated;

-- 4. data.json의 실습용 가상 메모 네 건 삽입
INSERT INTO notes (title, content)
VALUES
  ('과제', '실습용 가상 과제 기록'),
  ('포트폴리오', '실습용 가상 포트폴리오 기록'),
  ('아침 리추얼', '실습용 가상 리추얼 기록'),
  ('훈련 행정 자료', '실습용 가상 행정 기록');
